server:
  port: 8081
  servlet:
    context-path: /statement-processor

demo:
  csv: classpath:records.csv  # csv data filename in classpath
  xml: classpath:records.xml  # csv data filename in classpath
  json: classpath:records.json  # csv data filename in classpath

logging:
  level:
    org.springframework: INFO
    com.golinko: INFO
